In [1]:
import numpy as np
from random import randrange, uniform
import matplotlib.pyplot as plt
from scipy.stats import truncnorm

In [2]:
np_tweets=100
np_topics=10
nb_annotators=15
nb_labels=4

tweets_topics=np.zeros((np_topics,np_tweets))

items = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
for i in range(0,np_tweets):
  sum=0
  while(sum<1):
   topic=randrange(np_topics)
   if sum<1:
      items=[]
      k=0.1
      while(k<1-sum+0.1):
          items.append(k)
          k=round(k+0.1,1)
   rand_item =round( items[randrange(len(items))],1)
   if tweets_topics[topic,i]==0.0:
    tweets_topics[topic,i]=rand_item
    sum=round(sum+rand_item,1)
    #print(sum)
#print ('tweets_topics array')
#print (tweets_topics)

topics=[]
topics=np.zeros(np_topics)
for i in range(0,np_topics):
    for j in range(0,np_tweets):
        topics[i]=topics[i]+tweets_topics[i,j]
#print('topics',topics)


x=[]
likelihood=[]
annt_responses=np.zeros((nb_annotators,np_tweets))
annt_topics=np.full((nb_annotators,np_topics),1.0)

In [4]:
groundTruth=[]
for c in range(0,np_tweets):
    groundTruth.append(randrange(1,nb_labels+1,1))
print('groundTruth',groundTruth)

groundTruth [3, 3, 1, 4, 2, 2, 4, 3, 4, 1, 3, 3, 3, 2, 4, 4, 3, 1, 4, 2, 4, 1, 1, 3, 1, 4, 1, 2, 4, 4, 1, 4, 4, 1, 2, 2, 2, 4, 1, 2, 3, 2, 4, 1, 1, 1, 4, 3, 2, 2, 2, 3, 4, 1, 4, 4, 3, 4, 4, 4, 1, 3, 1, 1, 4, 3, 2, 2, 4, 3, 2, 1, 4, 1, 2, 1, 1, 4, 4, 1, 3, 3, 4, 3, 2, 2, 2, 1, 4, 2, 3, 4, 3, 3, 1, 1, 3, 1, 1, 3]


In [6]:
for m in range(0,nb_annotators):
 done=False
 while(done==False):
   val=np.random.normal(0.6, 0.3,1)#the accurcy for each annotater
   if val>0 and val<1:
       x.append(val)
       done=True

In [9]:
for m in range(0,nb_annotators):
 done=False
 while(done==False):
   val=np.random.normal(0.5, 0.3,1)#the Likelihood of response for each annotater
   if val>0 and val<1:
       likelihood.append(val)
       done=True

print(likelihood)       
for m in range(0,nb_annotators):
  done=False
  while(done==False):
  
   if x[m]>0 and x[m]<1:
    correct=np.random.binomial(1,x[m],np_tweets)
    for i in range(0,np_tweets):
        annotate=np.random.binomial(1,likelihood[m],1)
        if (annotate[0]!=0):
         #print('annotate',annotate[0],m,i)
         if correct[0]==1:   
          annt_responses[m,i]=groundTruth[i]
          for c in range(0,np_topics):
                if tweets_topics[c,i]!=0:
                    annt_topics[m,c]=round(annt_topics[m,c]+(tweets_topics[c,i]/topics[c]),2)
                    #print('here5',tweets_topics[c,i]/topics[c],c,i)
                    
                    #print('here',annt_topics[m,c],m,c)
         else:
           #print('not correct',m)
           annt_responses[m,i]=randrange(1,nb_labels+1,1)  
           if annt_responses[m,i]==groundTruth[i]:
               for c in range(0,np_topics):
                if tweets_topics[c,i]!=0:
                    annt_topics[m,c]=round(annt_topics[m,c]+(tweets_topics[c,i]/topics[c]),2)
                    #print('here22',tweets_topics[c,i]/topics[c],c,i)
                    
                    #print('here2',annt_topics[m,c],m,c)
           else:
               for c in range(0,np_topics):
                if tweets_topics[c,i]!=0:
                    annt_topics[m,c]=round(annt_topics[m,c]-(tweets_topics[c,i]/topics[c]),2)
                    #print('here32',tweets_topics[c,i]/topics[c],c,i)
                    #print('here3',annt_topics[m,c],m,c)
             
   done=True

[array([0.38803043]), array([0.55765854]), array([0.53873284]), array([0.4155723]), array([0.46951099]), array([0.61808876]), array([0.33675946]), array([0.44800386]), array([0.75267849]), array([0.41159811]), array([0.41643392]), array([0.40813428]), array([0.53615218]), array([0.43781753]), array([0.44752083]), array([0.11416424]), array([0.19891894]), array([0.3741544]), array([0.65194298]), array([0.14621934]), array([0.60137242]), array([0.84408131]), array([0.44610271]), array([0.93375454]), array([0.08942235]), array([0.21207946]), array([0.47549988]), array([0.2260297]), array([0.56704677]), array([0.28181093]), array([0.28453976]), array([0.64583553]), array([0.35873578]), array([0.62657585]), array([0.55032018]), array([0.52911955]), array([0.33869462]), array([0.5881967]), array([0.28412554]), array([0.58168294]), array([0.65520619]), array([0.19060749]), array([0.38880107]), array([0.32195528]), array([0.92990313])]


In [10]:
print('annotators ''responses')
print(annt_responses)

annotators responses
[[4. 0. 0. ... 0. 3. 0.]
 [0. 3. 0. ... 0. 0. 3.]
 [1. 0. 2. ... 4. 0. 1.]
 ...
 [0. 0. 1. ... 4. 4. 0.]
 [0. 0. 0. ... 1. 0. 3.]
 [2. 0. 2. ... 0. 3. 0.]]


In [11]:
annt_tpc=np.full((nb_annotators,np_topics),1.0)
agree=[]
totalsim=0
trueLabels=[]
for i in range(0,nb_annotators):
 agreement=0
 for j in range(0,nb_annotators):
    for z in range(0,np_tweets):
      if annt_responses[i][z]!=0:
       if annt_responses[i][z]==annt_responses[j][z] and i!=j:
         #print('here',i,j)
         agreement=agreement+1
 agree.append(agreement/(nb_annotators-1))
 totalsim=totalsim+agreement/(nb_annotators-1)
#print(agree)

for i in range(0,np_tweets):
 highsim=0.0
 truelabel=0
 for label in range(1,nb_labels+1):
     sim=0.0
     for j in range(0,nb_annotators):
         if annt_responses[j][i]==label:
             #sim=sim+agree[j]
             for c in range(0,np_topics):
              if tweets_topics[c,i]!=0:
               sim=sim+(agree[j]*annt_tpc[j,c])
     if highsim<sim:
         truelabel=label
         highsim=sim
 #print("highsim")
 #print(highsim, truelabel)        
 trueLabels.append(truelabel)
 if (annt_responses[j][i]==trueLabels[i]) :
          for c in range(0,np_topics):
              if tweets_topics[c,i]!=0:
                annt_tpc[j,c]=round(annt_tpc[j,c]+(tweets_topics[c,i]/topics[c]),2)
 else:
         for c in range(0,np_topics):
              if tweets_topics[c,i]!=0:
                annt_tpc[j,c]=round(annt_tpc[j,c]-(tweets_topics[c,i]/topics[c]),2)
#print('annt_tps')
#print(annt_topics)
#print(annt_tpc)

In [12]:
majority_voting=[]
for j in range(0,np_tweets):
        high=0
        s=0
        for x in range(1,nb_labels+1):
         s=0
         for i in range(0,nb_annotators):
            if annt_responses[i][j]==x:
                s=s+1
         if s>high:
          high=s
          majority=x
        majority_voting.append(majority)  
#======================================================                
print ("the groud truth")
print(groundTruth)
print ("the estimated labels")
print(trueLabels)
print('majority_voting')
print(majority_voting)


the groud truth
[3, 3, 1, 4, 2, 2, 4, 3, 4, 1, 3, 3, 3, 2, 4, 4, 3, 1, 4, 2, 4, 1, 1, 3, 1, 4, 1, 2, 4, 4, 1, 4, 4, 1, 2, 2, 2, 4, 1, 2, 3, 2, 4, 1, 1, 1, 4, 3, 2, 2, 2, 3, 4, 1, 4, 4, 3, 4, 4, 4, 1, 3, 1, 1, 4, 3, 2, 2, 4, 3, 2, 1, 4, 1, 2, 1, 1, 4, 4, 1, 3, 3, 4, 3, 2, 2, 2, 1, 4, 2, 3, 4, 3, 3, 1, 1, 3, 1, 1, 3]
the estimated labels
[3, 3, 1, 4, 2, 2, 4, 3, 4, 1, 3, 3, 3, 2, 4, 4, 3, 1, 4, 2, 4, 1, 3, 3, 1, 4, 1, 2, 4, 4, 1, 4, 4, 1, 2, 2, 2, 4, 1, 2, 3, 4, 4, 1, 1, 1, 2, 3, 2, 2, 2, 3, 4, 1, 4, 4, 3, 4, 4, 4, 1, 3, 1, 1, 4, 3, 2, 2, 4, 4, 2, 1, 4, 2, 2, 1, 1, 4, 4, 4, 3, 3, 4, 3, 2, 2, 1, 1, 4, 2, 3, 2, 3, 3, 1, 3, 3, 1, 1, 3]
majority_voting
[1, 3, 1, 4, 2, 2, 4, 3, 1, 1, 3, 3, 3, 2, 4, 4, 3, 1, 4, 2, 4, 1, 3, 3, 1, 4, 1, 2, 4, 4, 1, 1, 4, 1, 2, 1, 2, 4, 1, 2, 3, 4, 4, 1, 1, 1, 1, 3, 2, 2, 2, 3, 4, 1, 4, 4, 3, 4, 4, 4, 1, 4, 1, 1, 4, 3, 2, 2, 4, 4, 2, 1, 4, 2, 2, 1, 1, 4, 4, 4, 3, 3, 4, 3, 2, 2, 1, 1, 3, 2, 3, 2, 3, 3, 4, 3, 3, 1, 3, 3]


In [13]:
hits_algo1=0
hits_MV=0
for i in range(0,np_tweets):
    if groundTruth[i]==trueLabels[i]:
        hits_algo1=hits_algo1+1
    if majority_voting[i]==trueLabels[i]:
        hits_MV=hits_MV+1
print('accuracy of algo',hits_algo1/np_tweets)
print('accuracy of MV',hits_MV/np_tweets)   

accuracy of algo 0.91
accuracy of MV 0.91
